# Generated by Django 4.2.4 on 2023-08-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_rename_datatime_contact_date_alter_contact_desc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(max_length=50),
        ),
    ]
